## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"
title = "Tim Slifer"
theme = "triple-hyde"

## Site Settings
[params]
    #author = "Author"
    #title = "Title"
    description = "Building and scaling QA teams, promoting Culture of Quality"

    # sidebar, copyright & license
    authorimage = "/img/1.jpg"
    copyright = "Tim Slifer"
    since = 2025
    license = "CC BY-NC-ND"
    licenseURL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
    showBuiltWith = true

## Social Accounts
[params.social]
    github = "tim-slifer"
    linkedin = "timslifer"
    stackoverflow = "3763338/tim-slifer"

## Main Menu
# [[menu.main]]
#     name = "Posts"
#     weight = 100
#     identifier = "posts"
#     url = "/posts/"
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
